language: csharp
solution: WebShop.sln
install:
- nuget restore WebShop.sln
- nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
 - msbuild /p:Configuration=Release WebShop.sln
 - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./CheckOutFormTest.Tests/bin/Release/CheckOutFormTest.Tests.dll