language: csharp
solution: ./WebShop.sln

before_script:
- git submodule update --init --recursive

install:
- apt-get install nunit-console
- nuget restore ./WebShop.sln

script:
- xbuild ./WebShop.sln
- nunit-console ./CheckOutFormTest/unitTest


