language: csharp
sudo: required
mono: none
solution: ./WebShop.sln
dotnet: 3.1

install:
- dotnet restore ./WebShop.sln

script:
 - dotnet build ./WebShop.sln
 - dotnet test

before_deploy:
 - dotnet pack -c Release

deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push ./SampleSDK/bin/Release/SampleSDK.*.nupkg  -k $NUGET_API -s https://api.nuget.org/v3/index.json --skip-duplicate
  on:
    branch: master
