language: csharp
solution: WebShop.sln

before_script:
- git submodule update --init --recursive

install:
- nuget restore WebShop.sln
- nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner

script:
- msbuild /p:Configuration=Release WebShop.sln
- mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./CheckOutFormTest.Tests/bin/Release/CheckOutFormTest.Tests.dll


