USE [HM_Products]

/****** Object:  Table [dbo].[Tags]    Script Date: 28-08-2020 14:49:46 ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Tags](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[tag] [varchar](100) NOT NULL,
 CONSTRAINT [IX_Tags] UNIQUE NONCLUSTERED 
(
	[tag] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


