USE [HM_Products]

/****** Object:  Table [dbo].[BulletPoint]    Script Date: 02-09-2020 09:46:04 ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[BulletPoint](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[bulletpoint] [varchar](150) NULL,
 CONSTRAINT [PK_BulletPoint] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_BulletPoint] UNIQUE NONCLUSTERED 
(
	[bulletpoint] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[BulletPoint]  WITH CHECK ADD  CONSTRAINT [FK_BulletPoint_BulletPoint] FOREIGN KEY([ID])
REFERENCES [dbo].[BulletPoint] ([ID])

ALTER TABLE [dbo].[BulletPoint] CHECK CONSTRAINT [FK_BulletPoint_BulletPoint]
