//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.6.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>SearchFilters</summary>
	[PublishedModel("searchFilters")]
	public partial class SearchFilters : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public new const string ModelTypeAlias = "searchFilters";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SearchFilters, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public SearchFilters(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// column1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("column1")]
		public global::System.Collections.Generic.IEnumerable<string> Column1 => this.Value<global::System.Collections.Generic.IEnumerable<string>>("column1");

		///<summary>
		/// column1Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("column1Header")]
		public string Column1Header => this.Value<string>("column1Header");

		///<summary>
		/// column2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("column2")]
		public global::System.Collections.Generic.IEnumerable<string> Column2 => this.Value<global::System.Collections.Generic.IEnumerable<string>>("column2");

		///<summary>
		/// column2Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("column2Header")]
		public string Column2Header => this.Value<string>("column2Header");

		///<summary>
		/// column3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("column3")]
		public global::System.Collections.Generic.IEnumerable<string> Column3 => this.Value<global::System.Collections.Generic.IEnumerable<string>>("column3");

		///<summary>
		/// column3Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("column3Header")]
		public string Column3Header => this.Value<string>("column3Header");

		///<summary>
		/// column4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("column4")]
		public global::System.Collections.Generic.IEnumerable<string> Column4 => this.Value<global::System.Collections.Generic.IEnumerable<string>>("column4");

		///<summary>
		/// column4Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("column4Header")]
		public string Column4Header => this.Value<string>("column4Header");

		///<summary>
		/// searchrow
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.6.4")]
		[ImplementPropertyType("searchrow")]
		public global::System.Collections.Generic.IEnumerable<string> Searchrow => this.Value<global::System.Collections.Generic.IEnumerable<string>>("searchrow");
	}
}
